(() => {
  const shared = {
    previews: {
      egocentric: { type: "text", kicker: "RESEARCH · NUS", title: "Egocentric", caption: "Research direction · Responsibilities" },

      humanoid: { type: "video", src: "assets/media/egohumanoid-g1-fourier.mp4", poster: "assets/media/egohumanoid-g1-fourier-poster.jpg", alt: "G1 and Fourier-hand humanoid replay", kicker: "EGOHUMANOID · MIMICLITE", title: "Humanoid", caption: "ZED Mini → Human pose → G1 + Fourier hand" },
      manipulation: { type: "video", src: "assets/media/arm-teleop-grasp.mp4", poster: "assets/media/arm-teleop-grasp-poster.jpg", alt: "FAIRINO FR3 teleoperation on real hardware", kicker: "SERVO · TELEOP · FORCE", title: "Manipulation", caption: "Reference → Command → Actual" },
      drawry: { type: "image", src: "assets/media/drawry-prototype-poster.png", alt: "Drawry public product prototype", kicker: "PRODUCT · AI STORYTELLING", title: "Drawry", caption: "Drawing → Story → Family memory" },
    },
    a3u: {
      deployment: { type: "video", src: "assets/media/mimiclite-g1-deployment.mp4", poster: "assets/media/mimiclite-g1-deployment-poster.jpg", alt: "G1 real-hardware motion replay used to validate the MimicLite deployment path", caption: "G1 motion replay on real hardware" },
      asset: { type: "image", image: "assets/media/mimiclite-a3u-mujoco.png", alt: "MuJoCo model view used for A3U URDF and joint-order adaptation" },
      retarget: { type: "video", src: "assets/media/mimiclite-retarget-sim.mp4", poster: "assets/media/mimiclite-retarget-sim-poster.jpg", alt: "Live PICO input and A3U policy response in MuJoCo sim2sim; no real robot is shown", caption: "PICO input → policy response in MuJoCo sim2sim · no real robot shown" },
      policy: { type: "video", src: "assets/media/mimiclite-a3u-policy-sim.mp4", poster: "assets/media/mimiclite-a3u-policy-sim-poster.jpg", alt: "A3U policy response running in the sim2real-base-sim viewer; no PICO target or real robot is shown", caption: "A3U policy response in sim2sim · no PICO target view or real robot shown" },
      teleopHardware: { type: "video", src: "assets/media/mimiclite-a3u-pico-teleop-hardware.mp4", poster: "assets/media/mimiclite-a3u-pico-teleop-hardware-poster.jpg", alt: "PICO operator teleoperating an A3U humanoid on real hardware", caption: "PICO operator and A3U in the same real-hardware recording" },
      diagnosis: { type: "image", image: "assets/media/mimiclite-a3u-motion-comparison.png", alt: "A3U simulation plots comparing motion, body response and timing conditions" },
      collision: { type: "image", image: "assets/media/mimiclite-a3u-collision-overlay.png", alt: "A3U foot and body collision geometry diagnostic overlay" },
      control: { type: "image", image: "assets/media/mimiclite-a3u-delay-comparison.png", alt: "A3U simulation plots comparing controller gains and motion response" },
    },
    // The canonical journey uses these roles; the media keys above remain as
    // stable aliases for the existing viewer and older published links.
    a3uStageMedia: {
      deployment: { media: "deployment", visual: "video", label: "G1 / DEPLOYMENT", caption: "REAL HARDWARE · G1 motion replay" },
      model: { media: "asset", visual: "image", label: "MODEL / URDF" },
      collision: { media: "collision", visual: "image", label: "COLLISION / FOOT MODEL" },
      retarget: { media: null, visual: "process", label: "RETARGET / DATA" },
      policy: { media: "policy", visual: "video", label: "POLICY / SIM", caption: "A3U policy response in MuJoCo sim2sim · no PICO target view or real robot shown" },
      stability: { media: "diagnosis", secondaryMedia: "control", visual: "diagnostic", label: "STABILITY DEBUG" },
      teleop: { media: "teleopHardware", visual: "video", label: "PICO TELEOP", caption: "REAL HARDWARE · PICO TELEOP · operator and A3U in frame" },
    },
  };

  const zh = {
    skip: "跳到正文",
    metaDescription: "郭阳溢的个人主页。就读于新加坡国立大学 Smart Industrial and Digital Transformation 专业，方向为 Robotics and Automation；研究与项目包括 Egocentric、Humanoid、机器人控制与真机实验。",
    footerTop: "回到顶部 ↑",
    header: { status: "CURRENTLY · NUS ROBOTICS" },
    nav: { work: "项目", path: "路径", tech: "技术", contact: "联系", menu: "菜单" },
    menu: { label: "项目" },
    hero: {
      kicker: "ROBOTICS · NUS · SINGAPORE",
      titleText: "你好，我是郭阳溢。",
      title: "<span class=\"title-line title-line--greeting\"><span>你好，</span></span><span class=\"title-line title-line--identity\"><span>我是郭阳溢。</span></span>",
      deck: "我从本科开始就在做机器人，从机械结构、嵌入式和视觉，到后来的机械臂控制、人形机器人和多模态数据。",
      deckHtml: "<span class=\"hero-deck-line\">我从本科开始就在做机器人，</span><span class=\"hero-deck-line\">从机械结构、嵌入式和视觉，到后来的机械臂控制、人形机器人和多模态数据。</span>",
      deckSecond: "现在在 NUS，专注于 Egocentric 多模态人体数据采集系统，主要处理设备接入、标定、同步与记录。项目仍在起步阶段。",
      deckThird: "相比纯仿真，我更喜欢做真机实验，很多问题也是在实际调试里才真正遇到的。",
      primary: "查看项目", secondary: "查看当前项目", scroll: "SCROLL",
    },
    now: {
      title: "现在在做",
      egoCopy: "NUS 当前的研究方向是 Egocentric 多模态人体数据采集，项目处于早期阶段。",
      egoFooter: "EGO RESEARCH · SYSTEM INTEGRATION · EXPERIMENT SUPPORT",


      focus: "Egocentric 多模态人体数据采集研究。",
      copy: "现在在 <strong>NUS</strong>，专注于 <strong>Egocentric 多模态采集</strong>。",
      link: "更多项目",
    },
    projects: {
      title: "项目",
      intro: "从人体动作到机器人执行，这些项目记录了数据处理、运动控制与真机调试中的具体工作。",
      egoSubtitle: "多模态人体数据采集与实验系统",
      egoCopy: "Egocentric 研究聚焦多模态人体数据采集，当前工作包括系统集成、实验支持与数据质量。",


      open: "查看详情",
      humanoid: "EgoHumanoid · MimicLite · G1 / A3U",
      humanoidCopy: "EgoHumanoid 把采下的人体动作同步回放到 G1 和五指手。MimicLite 从开源 G1 方案的部署复现延伸到 A3U，已经完成模型适配与真机遥操作，动作质量正在继续调整。",
      manipulation: "机械臂运动控制、遥操作与力交互",
      manipulationCopy: "样条运动 SDK 已在莆田 PUMA 鞋厂使用，驱动机械臂沿给定路径连续运动。FR3 主从遥操作支持动作跟随，2-DoF 力反馈实验把从臂的接触阻力传回主臂，操作者可以在手中感到接触变化。",
      drawry: "AI 亲子故事产品",
      drawryCopy: "孩子画下的人物和场景，会变成可以一起读的故事与分镜。小绘书的原型把上传画作、生成故事和家庭空间连在一起，原画与故事可以保存下来，留给孩子和家长以后翻看。",
    },
    path: {
      title: "我的路径",
      intro: "本科阶段我就开始做机器人，最早完成了一套同时涉及机械、嵌入式和视觉的物流搬运机器人。之后做过视觉部署、机械臂控制和真机实验，2026 年开始接触 Whole‑body VLA 和人形机器人，现在专注于 Egocentric 多模态采集。",
      originKicker: "本科毕业设计 · 真机",
      originCaption: "物流搬运机器人：目标识别、搬运、定点放置与返回",
      items: [
        { title: "第一套完整机器人系统", copy: "本科毕业设计中，我把机械结构、STM32 控制与树莓派上的 OpenCV 视觉接到一起，完成识别、搬运、定点放置和返回。第一次需要为整台机器人的运行负责，也由此开始重视模块之间的接口与调试。" },
        { title: "视觉部署", copy: "在无人机亚洲象检测项目中，我处理数据、训练并优化 YOLOv11，将模型部署到边缘设备，再用真实视频流和现场测试检查效果。关注点也从离线模型结果，延伸到计算资源和实际拍摄条件。" },
        { title: "机械臂与力控制", copy: "在中科慧灵实习时，我开发样条运动 SDK、搭建主从遥操作，也做六维力和柔顺控制。真机上的停顿、抖动和接触响应，让我开始把控制周期、滤波、坐标变换、动力学补偿和安全保护放在一起考虑。" },
        { title: "Whole‑body VLA 与 Humanoid", copy: "参与 Whole‑body VLA / WAM 的数据工作时，我实现 PICO、SMPL 与 RGB 同步，整理 HDF5 数据和动作映射，并检查回放质量。在 EgoHumanoid 与 MimicLite 中继续处理五指手模型、G1 部署和 A3U 适配，逐步接触人体数据到机器人动作的完整过程。" },
        { title: "Egocentric 多模态采集", copy: "来到 NUS 后，我专注于 Egocentric 多模态人体数据采集系统，重点推进设备接入、标定、时间同步、数据记录与质量检查。项目仍在起步阶段。" },
      ],
    },
    academic: {
      identity: "新加坡国立大学 · 硕士在读 · 机器人与自动化方向",
      degreeLabel: "学位",
      degree: "新加坡国立大学 · 硕士在读 · 2026–2028",
      programmeLabel: "专业",
      programme: "Smart Industrial and Digital Transformation",
      trackLabel: "方向",
      track: "Robotics and Automation",
    },
    tech: {
      title: "常用技术与平台",
      groups: [
        { title: "机器人与控制", copy: "实现路径插值、实时指令下发、输入滤波与力反馈，并在真机上调试连续性和响应。" },
        { title: "人体数据与动作", copy: "把传感器记录对齐到统一时间轴，处理人体到机器人的动作映射，并用回放检查数据质量。" },
        { title: "仿真与硬件", copy: "接入机器人模型和设备接口，在仿真中检查动作，再用真机响应定位模型、时序与控制问题。" },
      ],
    },
    contact: {
      title: "欢迎联系我。",
      copy: "我目前专注于 Egocentric 多模态人体数据采集，也希望继续交流机器人控制与人体数据相关的工作。欢迎交流真机调试和示范采集中的问题，也欢迎通过邮件联系研究合作与工作机会。",
    },
    project: { back: "全部项目", next: "下一个项目" },
    ego: {
      "secondaryLabel": "研究方向",
      "lead": "Egocentric 是我目前在 NUS 专注的多模态人体数据采集研究方向，项目处于早期阶段。",
      "leadSecond": "个人工作聚焦系统集成、实验支持与数据质量。",
      "focusItems": [
        "Egocentric 研究",
        "多模态人体数据",
        "实验系统"
      ],
      "roleTitle": "我的职责",
      "roles": [
        {
          "title": "系统集成",
          "copy": "参与采集系统的设备接入与集成。"
        },
        {
          "title": "实验支持",
          "copy": "推进标定、时间同步与数据记录工作。"
        },
        {
          "title": "数据质量",
          "copy": "开展数据质量检查，整理实验流程与文档。"
        }
      ]
    },
    humanoid: {
      secondaryLabel: "我的工作",
      streamNotes: ["采集、同步与动作映射", "开源复现与跨机型适配"],
      lead: "人形机器人上的工作分成 EgoHumanoid 和 MimicLite 两部分。EgoHumanoid 里搭建采集与回放流程，接入五指手模型。MimicLite 基于开源方案复现 G1 部署，随后适配 A3U 的模型、动作数据和真机接口。",
      egoTitle: "时间同步与机器人回放",
      egoIntro: "我通过重采样、插值和丢帧处理对齐 RGB 与 SMPL 数据，接入 HDF5 / SVO2 记录与 G1 回放。针对手模型不匹配，我将旧三指手替换为 Fourier 五指模型，再通过同步回放检查坐标、关节映射和姿态跳变。",
      facts: [
        { label: "INPUT", value: "PICO + ZED Mini RGB-D" },
        { label: "RECORD", value: "HDF5 + SVO2" },
        { label: "ALIGNMENT", value: "60 Hz RGB + 100 Hz SMPL → 50 Hz" },
        { label: "REPLAY", value: "G1 + Fourier five-finger" },
      ],
      mimicTitle: "从 G1 到 A3U",
      mimicIntro: "基于开源 MimicLite，我先复现 G1 的 sim2sim、Orin 推理与通信部署，再适配 A3U 的关节顺序、控制接口和动作数据。迁移中更花时间的是定位本体差异：结合碰撞模型、控制增益和响应曲线，迭代训练并验证真机动作。",
      syncSource: "三段画面来自同一条回放链路；切换焦点不会改变共享时间轴。",
      stageMeta: { context: "要解决的问题", evidence: "实现与验证", result: "结果与边界" },
      g1SummaryLabel: "G1",
      g1Title: "G1 部署与真机验证",
      g1Copy: "基于开源 MimicLite，我复现 G1 部署流程，搭建 Orin 推理环境并测试 inline、ZMQ + bridge 通信，再用行走、跳跃和运动参考动作检查真机执行，确认从策略推理到机器人动作的对应关系。",
      g1MediaLabel: "MIMICLITE · UNITREE G1",
      g1MediaCaption: "真机任务 · 扔垃圾",
      g1OnCamera: "画面人物：郭阳溢",
      g1MotionsLabel: "REFERENCE MOTIONS",
      a3uCaseLabel: "A3U",
      a3uSteps: [
        { kicker: "01 / ROBOT MODEL", title: "A3U 模型适配", copy: "我把 A3U 已有的 URDF 接入工程，核对关节定义与顺序，适配初始配置和位置控制接口，为动作重定向与部署准备新本体模型。" },
        { kicker: "02 / RETARGET", title: "A3U 动作 retarget", copy: "针对 G1 动作直接迁移后质量下降的问题，我适配 HHTools 重定向流程，用 any4hdmi 检查生成动作并筛除低质量结果，再将可用数据送入 A3U 训练。" },
        { kicker: "03 / TRAINING", title: "A3U Policy 训练", copy: "我用重新整理的 A3U 动作数据迭代训练，在 sim2sim 中检查后部署到真机。第一版能够行走，但站立和复杂动作仍不稳定，需要继续调整数据和训练参数。" },
        { kicker: "04 / REAL ROBOT", title: "真机稳定性调试", copy: "面对仿真正常、真机高频抖动的差异，我分别检查足底碰撞、响应时序和控制增益。调整 Kp / Kd 并重新训练后，明显抖动基本消失，简单动作可以执行。" },
        { kicker: "05 / PICO TELEOP", title: "PICO 遥操作", copy: "我先在 MuJoCo 中检查 PICO 输入与策略响应，再接入 A3U 真机，核对动作对应、响应时序与稳定性，完成手臂、身体动作和行走测试。" },
      ],
      a3uStageOrder: ["deployment", "model", "collision", "retarget", "policy", "stability", "teleop"],
      a3uStageLabels: {
        deployment: "G1 / DEPLOYMENT",
        model: "MODEL / URDF",
        collision: "COLLISION / FOOT MODEL",
        retarget: "RETARGET / DATA",
        policy: "POLICY / SIM",
        stability: "STABILITY DEBUG",
        teleop: "PICO TELEOP",
      },
      a3uStages: {
        deployment: {
          kicker: "01 / G1 / DEPLOYMENT",
          title: "G1 上的部署链路",
          copy: "我复现开源 MimicLite 的 G1 部署：先完成电脑端 sim2sim，再搭建机载 Orin 推理环境，测试 inline 与 ZMQ + bridge 通信，最后用参考动作核对真机执行。工作重点是把模型、推理和机器人接口接通并逐段验证。",
          media: "deployment",
          visual: "video",
          visualLabel: "SIM2SIM → ORIN → REAL G1",
          caption: "REAL HARDWARE · G1 动作复现",
          context: "同一策略需要从电脑验证转到机载推理，并接入真机通信。",
          evidence: "Orin 部署与推理、inline / ZMQ + bridge 通信测试。",
          result: "完成机载部署与通信测试，并验证行走、跳跃和运动参考动作。",
        },
        model: {
          kicker: "02 / MODEL / URDF",
          title: "A3U 模型与接口",
          copy: "我接入 A3U 已有的 URDF 与模型文件，重新核对关节顺序、初始姿态和动作维度，再按位置输入为主的真机 SDK 适配部署接口。这一步先解决模型与指令是否对应，避免将接口错误带入后续训练。",
          media: "asset",
          visual: "image",
          visualLabel: "MUJOCO MODEL",
          context: "A3U 的关节定义、模型文件和真机接口都与 G1 不同。",
          evidence: "接入 URDF / MJCF，核对关节顺序、初始配置与位置接口。",
          result: "完成新本体模型与接口适配，用于后续动作重定向和策略验证。",
        },
        collision: {
          kicker: "03 / COLLISION / FOOT MODEL",
          title: "脚底与碰撞体",
          copy: "排查 A3U 的站立抖动时，我检查足底和全身碰撞体的位置与范围，并尝试 Capsule 脚部简化模型。碰撞几何、Kp / Kd 和动作延迟分开验证，避免仅凭仿真画面就把真机问题归因于某一个参数。",
          media: "collision",
          visual: "image",
          visualLabel: "COLLISION OVERLAY",
          context: "脚底接触和碰撞几何会直接影响站立与落脚。",
          evidence: "核对四视角碰撞体叠加图，比较脚部简化方案。",
          result: "确认碰撞体位置与范围；对真机稳定性的影响还需结合控制参数判断。",
        },
        retarget: {
          kicker: "04 / RETARGET / DATA",
          title: "动作数据 retarget",
          copy: "G1 的动作在 A3U 上能够运行，但不能直接保留原来的动作质量。我适配 HHTools 重定向流程，将 PICO / SMPL 动作转为 A3U 训练数据，再用 any4hdmi 检查输出并人工筛选低质量结果，减少不合适动作进入训练。",
          media: null,
          visual: "process",
          visualLabel: "PICO / SMPL → RETARGET → NPZ → TRAINING",
          process: ["PICO / SMPL", "motion retarget", ".npz", "policy training"],
          context: "G1 的 motion 不能直接解决 A3U 的本体差异，需要重新准备数据。",
          evidence: "适配 HHTools，生成 .npz，并用 any4hdmi 检查动作。",
          result: "接通自采、重定向、筛选与训练流程；仍需人工处理部分低质量结果。",
        },
        policy: {
          kicker: "05 / POLICY / SIM",
          title: "Policy 与仿真响应",
          copy: "我使用重定向后的 A3U 数据迭代策略训练，先通过 sim2sim 检查动作，再部署到真机验证。第一版已经能够行走，但站立和复杂动作仍不稳定；数据比例与训练参数继续调整，本体碰撞差异则在真机调试中单独排查。",
          media: "policy",
          visual: "video",
          visualLabel: "POLICY RESPONSE · SIM2SIM",
          caption: "A3U policy 在 MuJoCo 中的 sim2sim 响应 · 未显示 PICO target 或真机",
          context: "新本体需要重新准备动作数据，并验证策略能否迁移到真机。",
          evidence: "A3U 数据训练、sim2sim 检查与受保护真机验证。",
          result: "仿真中可以行走，随后也完成了真机部署；站立和复杂动作仍不稳定。",
        },
        stability: {
          kicker: "06 / STABILITY DEBUG",
          title: "真机稳定性调试",
          copy: "面对仿真准备姿态正常、真机却高频抖动的差异，我结合身体响应、腿部目标与首帧状态，分别排查碰撞、时序和控制增益。调整 Kp / Kd 并重新训练后，明显抖动基本消失，简单动作可以执行。",
          media: "diagnosis",
          secondaryMedia: "control",
          visual: "diagnostic",
          visualLabel: "RESPONSE / GAIN DIAGNOSTICS",
          context: "准备姿态在仿真正常，真机却出现高频抖动和 CLI 首帧跳变。",
          evidence: "对照身体响应与腿部目标，比较 Kp / Kd 和动作延迟设置。",
          result: "调整 Kp / Kd 并重新训练后，明显抖动基本消失，简单动作可以执行。",
        },
        teleop: {
          kicker: "07 / PICO TELEOP",
          title: "PICO 遥操作",
          copy: "我把 PICO 输入接入 A3U 遥操作流程，先在 MuJoCo 中检查动作映射与策略响应，再到真机上核对手臂、身体和行走动作。调试时同时关注动作是否对应、响应是否及时，以及机器人能否保持稳定。",
          media: "teleopHardware",
          visual: "video",
          visualLabel: "REAL HARDWARE · PICO TELEOP",
          caption: "REAL HARDWARE · PICO 操作者与 A3U 同画面",
          context: "人体输入需要经过动作映射和策略，最终形成稳定的真机响应。",
          evidence: "MuJoCo 输入检查与 A3U 真机遥操作，录像中可对照人机动作。",
          result: "输入与机器人动作能够正常对应，A3U 可完成手臂跟随、身体动作和行走响应。",
        },
      },
      outcomeTitle: "迁移结果与动作质量",
      outcomeDone: "我完成了从 G1 复现到 A3U 模型、数据和接口适配，并推进策略训练与真机验证。调整 Kp / Kd 并重新训练后，明显高频抖动基本消失；PICO 已能驱动手臂、身体和行走响应，简单动作可以执行。",
      outcomeOpen: "进一步提升动作质量时，我需要平衡不同动作的数据比例。加入地面动作后，大幅度动作有所改善，但部分原有动作退化；浅蹲可用，深蹲仍易失稳。整体尚未达到 G1 原策略的表现，训练与数据调整仍在继续。",
      evidenceTitle: "A3U 适配与验证",
      evidenceIntro: "我分别适配 A3U 的模型、动作数据与控制接口，再进行策略训练和真机测试。通过对照仿真响应与真机动作，定位迁移后的模型、时序和控制问题。",
      a3uOpenLabel: "查看原尺寸证据图",
      a3u: {
        asset: { kicker: "02 / MODEL / URDF", title: "A3U 模型适配", copy: "我接入 A3U 的 URDF 和模型文件，核对关节顺序与初始配置，再在 MuJoCo 中检查载入结果，为动作数据和训练准备新本体。" },
        retarget: { kicker: "04 / RETARGET / DATA", title: "动作数据 retarget", copy: "我适配 PICO / SMPL 到 HHTools 的重定向流程，用 any4hdmi 检查 .npz 动作，筛选低质量结果后再用于 A3U 策略训练。" },
        diagnosis: { kicker: "06 / STABILITY DEBUG", title: "动作与响应诊断", copy: "我对照不同动作、速度和延迟下的身体响应，定位抖动、腿部目标变化与跟随误差，再检查对应的模型和控制参数。" },
        collision: { kicker: "03 / COLLISION / FOOT MODEL", title: "脚底碰撞", copy: "我用四视角叠加图核对脚底与全身碰撞体，并尝试 Capsule 脚部简化模型，单独检查接触几何对动作的影响。" },
        control: { kicker: "06 / GAIN DIAGNOSTICS", title: "控制增益", copy: "我比较不同 Kp / Kd 下的身体倾角、陀螺仪与腿部目标，以响应曲线作为调参和重新训练的依据。" },
        policy: { kicker: "05 / POLICY / SIM", title: "Policy 与仿真响应", copy: "我用 sim2real-base-sim 检查 A3U 策略的动作响应，再进行真机验证；这里保留的是单机仿真画面。" },
        teleop: { kicker: "07 / PICO TELEOP", title: "A3U 真机遥操作", copy: "我将 PICO 输入接入 A3U，在真机上检查手臂、身体和行走响应。录像中人机同框，便于对照动作是否对应。" },
      },
    },
    manipulation: {
      secondaryLabel: "技术概况",
      profileLabels: { api: "控制接口", rate: "FR3 ServoJ 循环", environment: "实验环境" },
      lead: "机械臂控制这部分主要来自中科慧灵的实习。独立开发样条运动 SDK 之后，搭建 FR3 主从遥操作时复用了其中的插值方法。2-DoF 平台用来做重力补偿和力反馈实验，操作者能在主臂上感受到从臂接触物体时的阻力。",
      motionTitle: "样条运动 SDK",
      motionIntro: "我独立开发样条运动 SDK，将五次位置插值、Rodrigues 姿态插值、转角过渡与 ServoCart 下发整合起来，并加入 IK 预检、关节连续性检查和队列节流，处理路径衔接与到点不及时造成的停顿。SDK 已用于莆田 PUMA 鞋厂机械臂。",
      teleopTitle: "FR3 主从遥操作",
      teleopIntro: "为降低实现成本，我复用样条运动 SDK 的插值方法搭建 FR3 主从遥操作，让后台采样与 125 Hz 控制循环并行。输入更新最新待处理目标，切换时接续连续轨迹；再对照原始输入、滤波、指令和实际位置，检查抖动与跟随偏差。",
      forceNav: "2-DoF 力反馈",
      forceTitle: "<span class=\"heading-phrase\">2‑DoF 接触力矩</span>与力反馈",
      forceIntro: "我在 2-DoF 主从机械臂上实现重力补偿、关节跟随与接触力反馈。用电机力矩减去模型估算的重力项，再通过迟滞判断和非对称低通抑制干扰，将接触阻力传回主臂，让操作者能感知从臂的接触变化。",
    },
    drawry: {
      name: "小绘书",
      secondaryLabel: "我的职责",
      lead: "小绘书从孩子的一幅画出发，尝试做一款可以和家长一起读故事的产品。团队把想法做成了演示原型，我主要负责功能细化和交互逻辑，也参与页面设计与演示。",
      title: "从儿童画到故事",
      intro: "我围绕孩子上传画作、家长共读故事的过程设计关键页面，明确每一步的输入、生成内容与下一步操作。原画、故事和共读记录保存在家庭空间，让一次生成能够继续被阅读和回看。",
      steps: { upload: "上传画作", understand: "理解画面", story: "生成故事", family: "家庭空间" },
      contributionTitle: "我做的部分",
      contributions: [
        { title: "产品与交互", copy: "负责功能细化与交互逻辑，将亲子使用过程拆成关键页面和操作步骤。" },
        { title: "AI 工作流与原型", copy: "梳理画面理解、故事与分镜生成的输入输出，参与 MVP 原型设计。" },
        { title: "验证与演示", copy: "参与原型演示与路演材料准备，用完整使用流程说明产品想法。" },
      ],
      videoCaption: "产品原型演示 · 已静音",
      states: {
        upload: { kicker: "01 / 上传画作", title: "上传画作", copy: "以孩子的原画作为故事的起点。", output: "上传画作" },
        understand: { kicker: "02 / 理解画面", title: "理解画面", copy: "提取人物、物体与场景，保留画面里的线索。", output: "人物 · 物体 · 场景" },
        story: { kicker: "03 / 生成故事", title: "生成故事", copy: "将画面线索组织成可共读的故事与分镜。", output: "故事 · 分镜" },
        family: { kicker: "04 / 家庭空间", title: "家庭空间", copy: "让原画、生成故事和共读记录能够一起回看。", output: "画作 · 故事 · 共读记录" },
      },
    },
  };

  const en = {
    skip: "Skip to content",
    metaDescription: "I'm Yangyi Guo, a master's student in Smart Industrial and Digital Transformation at NUS, on the Robotics and Automation track. I build motion-control software, work on humanoid deployment and focus on egocentric multimodal data capture.",
    footerTop: "Back to top ↑",
    header: { status: "CURRENTLY · NUS ROBOTICS" },
    nav: { work: "Projects", path: "Path", tech: "Tech", contact: "Contact", menu: "Menu" },
    menu: { label: "PROJECTS" },
    hero: {
      kicker: "ROBOTICS · NUS · SINGAPORE",
      titleText: "Hi, I'm Yangyi.",
      title: "<span class=\"title-line title-line--greeting\"><span>Hi,</span></span><span class=\"title-line title-line--identity\"><span>I'm Yangyi.</span></span>",
      deck: "I got into robotics by building a whole robot, from its mechanics and embedded control to its vision. That led me to motion-control software, humanoids and human-motion data.",
      deckHtml: "<span class=\"hero-deck-line\">I got into robotics by building a whole robot.</span><span class=\"hero-deck-line\">Mechanics, embedded control and vision led me to motion-control software, humanoids and human-motion data.</span>",
      deckSecond: "I'm now at NUS, focused on egocentric multimodal data capture. I work on sensor integration, calibration, synchronization and recording. The project is at an early stage.",
      deckThird: "I love getting a robot moving on real hardware. That's where a timing bug, a poor mapping or an unexpected contact becomes something I can investigate and fix.",
      primary: "View projects", secondary: "Current work", scroll: "SCROLL",
    },
    now: {
      title: "What I’m working on",
      egoCopy: "Current research at NUS focuses on Egocentric multimodal human-data capture. The project is at an early stage.",
      egoFooter: "EGO RESEARCH · SYSTEM INTEGRATION · EXPERIMENT SUPPORT",


      focus: "Egocentric research",
      copy: "At NUS, I focus on <strong>egocentric multimodal data capture</strong>.",
      link: "More projects",
    },
      projects: {
        title: "Projects",
      intro: "The projects where I've spent the most time building, testing and figuring out why a robot didn't do what I expected.",
      egoSubtitle: "Multimodal human sensing and experiment infrastructure",
      egoCopy: "Egocentric research into multimodal human-data capture, with work on system integration, experiment support and data quality.",


      open: "Open project",
      humanoid: "EgoHumanoid · MimicLite · G1 / A3U",
      humanoidCopy: "I built synchronized human-data capture and robot replay, reproduced open-source MimicLite on G1, and adapted A3U's model, motion data and interfaces for policy training and hardware tests.",
      manipulation: "Servo motion · teleoperation · force feedback",
      manipulationCopy: "I independently built a spline-motion SDK used at a PUMA footwear factory in Putian, reused its interpolation methods for FR3 teleoperation, and implemented gravity compensation and contact torque feedback on a 2-DoF setup.",
      drawry: "An AI story product built from children's drawings",
      drawryCopy: "On the Drawry team, I refined features and interactions and helped design the prototype. My focus was connecting children's drawings, AI-generated stories and shared family reading.",
    },
    path: {
      title: "How I got here",
      intro: "My undergraduate logistics robot got me hooked on building across disciplines. I connected mechanics, embedded control and vision, then moved into field deployment, robot-arm control and hardware experiments. Whole-body VLA and humanoid work followed in 2026. At NUS, those interests now meet in egocentric multimodal data capture.",
      originKicker: "UNDERGRADUATE THESIS · REAL HARDWARE",
      originCaption: "Logistics robot: target detection, transport, fixed-point placement and return",
      items: [
        { title: "My first complete robot", copy: "For my undergraduate thesis, I built the mechanism and connected STM32 control with Raspberry Pi / OpenCV vision, bringing detection, transport, placement and return into one working robot." },
        { title: "Vision in the field", copy: "I prepared data, trained and optimized YOLOv11, and deployed it to an edge device for aerial Asian-elephant detection. Testing real video streams and joining field validation brought compute limits and changing camera conditions into my model-development work." },
        { title: "Robot arms and force", copy: "At Zhongke Huiling, I built a spline-motion SDK and FR3 teleoperation, alongside six-axis force and compliant-control work. I tested timing, filtering, coordinate transforms and dynamics compensation on hardware." },
        { title: "Whole‑body data and humanoids", copy: "For Whole-body VLA / WAM, I implemented PICO, SMPL and RGB synchronization, organized HDF5 data and checked motion replay. EgoHumanoid and MimicLite took me further into five-finger models, G1 deployment and A3U adaptation." },
        { title: "Egocentric multimodal capture", copy: "At NUS, I focus on egocentric multimodal data capture, working on sensor integration, calibration, synchronization, recording and quality checks. The project is at an early stage." },
      ],
    },
    academic: {
      identity: "NUS master's student · Robotics and Automation",
      degreeLabel: "Degree",
      degree: "NUS · Master's student · 2026–2028",
      programmeLabel: "Programme",
      programme: "Smart Industrial and Digital Transformation",
      trackLabel: "Track",
      track: "Robotics and Automation",
    },
    tech: {
      title: "Tools I work with",
      groups: [
        { title: "Robotics & control", copy: "I implement trajectory interpolation, real-time command streaming, input filtering and force feedback, then test continuity and response on hardware." },
        { title: "Human data & motion", copy: "I align sensor streams, prepare human-to-robot motion mappings and use synchronized replay to find dropped frames, pose jumps and data-quality issues." },
        { title: "Simulation & hardware", copy: "I integrate robot models and device interfaces, check motions in simulation and use hardware response to investigate model, timing and control errors." },
      ],
    },
    contact: {
      title: "Let’s talk robots.",
      copy: "I'm focused on egocentric multimodal data capture and would love to meet people working on robot control and human demonstrations. Email me to swap ideas about a hardware problem, talk about data capture, or discuss research collaborations and engineering roles.",
    },
    project: { back: "All projects", next: "Next project" },
    ego: {
      "secondaryLabel": "Research direction",
      "lead": "At NUS, I focus on Egocentric research into multimodal human-data capture. The project is at an early stage.",
      "leadSecond": "My responsibilities cover system integration, experiment support and data quality.",
      "focusItems": [
        "Egocentric Research",
        "Multimodal Human Data",
        "Experimental Systems"
      ],
      "roleTitle": "My responsibilities",
      "roles": [
        {
          "title": "System integration",
          "copy": "Contribute to device integration for the capture system."
        },
        {
          "title": "Experiment support",
          "copy": "Work on calibration, synchronization and data recording."
        },
        {
          "title": "Data quality",
          "copy": "Check data quality and document experimental procedures."
        }
      ]
    },
    humanoid: {
      secondaryLabel: "My work",
      streamNotes: ["Human data, sync + replay", "Open-source deployment + adaptation"],
      lead: "Getting human motion to work on different bodies draws me to humanoids. I built EgoHumanoid's data capture, sync and replay, reproduced open-source MimicLite on G1, and adapted A3U's model, data and interfaces for training and hardware tests.",
      egoTitle: "Synchronization and robot replay",
      egoIntro: "I aligned RGB and SMPL through resampling, interpolation and dropped-frame handling, connecting HDF5 / SVO2 records with G1 replay. I replaced the old three-finger hand with a Fourier five-finger model and used synchronized replay to check coordinate frames, joint mappings and pose jumps.",
      facts: [
        { label: "INPUT", value: "PICO + ZED Mini RGB-D" },
        { label: "RECORD", value: "HDF5 + SVO2" },
        { label: "ALIGNMENT", value: "60 Hz RGB + 100 Hz SMPL → 50 Hz" },
        { label: "REPLAY", value: "G1 + Fourier five-finger" },
      ],
      mimicTitle: "From G1 to A3U",
      mimicIntro: "I first reproduced open-source MimicLite's G1 deployment, including sim2sim, Orin inference and communication. Moving to A3U meant adapting joint order, control interfaces and motion data. The harder work was investigating body differences through collision models, response plots, gain tuning and hardware validation.",
      syncSource: "The three views come from one replay chain; changing focus keeps the shared timeline intact.",
      stageMeta: { context: "CHALLENGE", evidence: "MY APPROACH", result: "RESULT" },
      g1SummaryLabel: "G1",
      g1Title: "G1 deployment and hardware validation",
      g1Copy: "Starting from open-source MimicLite, I reproduced G1 deployment, set up Orin inference and tested inline and ZMQ + bridge communication. I checked walk, jump and fight/sports reference motions on hardware to verify the full deployment.",
      g1MediaLabel: "MIMICLITE · UNITREE G1",
      g1MediaCaption: "REAL-HARDWARE TASK · RUBBISH DISPOSAL",
      g1OnCamera: "ON CAMERA: YANGYI GUO",
      g1MotionsLabel: "REFERENCE MOTIONS",
      a3uCaseLabel: "A3U",
      a3uSteps: [
        { kicker: "01 / ROBOT MODEL", title: "A3U model adaptation", copy: "I integrated A3U's existing URDF, checked joint definitions and ordering, and adapted the initial configuration and position-control interface before moving on to retargeting and deployment." },
        { kicker: "02 / RETARGET", title: "A3U motion retarget", copy: "When G1 motions lost quality on A3U, I adapted the HHTools retargeting flow, inspected the outputs with any4hdmi and filtered low-quality motions before using them for training." },
        { kicker: "03 / TRAINING", title: "A3U policy training", copy: "I trained on the prepared A3U motions, checked the policy in sim2sim and deployed it to hardware. The first version could walk, but standing and complex motions still needed better data balance and training settings." },
        { kicker: "04 / REAL ROBOT", title: "Hardware stability debugging", copy: "A3U looked stable in simulation but shook on hardware. I investigated foot collision, response timing and control gains separately. After Kp / Kd tuning and retraining, the visible shaking largely disappeared and simple motions ran steadily." },
        { kicker: "05 / PICO TELEOP", title: "PICO teleoperation", copy: "I checked PICO input and policy response in MuJoCo before connecting A3U hardware, then tested arm, body and walking responses for motion correspondence, timing and stability." },
      ],
      a3uStageOrder: ["deployment", "model", "collision", "retarget", "policy", "stability", "teleop"],
      a3uStageLabels: {
        deployment: "G1 / DEPLOYMENT",
        model: "MODEL / URDF",
        collision: "COLLISION / FOOT MODEL",
        retarget: "RETARGET / DATA",
        policy: "POLICY / SIM",
        stability: "STABILITY DEBUG",
        teleop: "PICO TELEOP",
      },
      a3uStages: {
        deployment: {
          kicker: "01 / G1 / DEPLOYMENT",
          title: "Deployment path on G1",
          copy: "I reproduced the open-source MimicLite deployment on G1: computer-side sim2sim, onboard Orin inference, and inline and ZMQ + bridge communication. I verified each connection with reference motions on hardware, bringing the model, inference environment and robot interface together.",
          media: "deployment",
          visual: "video",
          visualLabel: "SIM2SIM → ORIN → REAL G1",
          caption: "REAL HARDWARE · G1 MOTION REPLAY",
          context: "Move a validated policy from the computer to onboard inference and real-robot communication.",
          evidence: "Set up Orin inference and tested inline and ZMQ + bridge communication.",
          result: "Completed onboard deployment and checked walk, jump and fight/sports reference motions on G1.",
        },
        model: {
          kicker: "02 / MODEL / URDF",
          title: "A3U model and interface",
          copy: "I integrated A3U's existing URDF and model files, checking joint order, initial poses and action dimensions. I adapted deployment to its primarily position-driven hardware SDK, verifying command mappings before training.",
          media: "asset",
          visual: "image",
          visualLabel: "MUJOCO MODEL",
          context: "A3U uses different joint definitions, model files and hardware interfaces from G1.",
          evidence: "Integrated URDF / MJCF, verified joint order and initial state, and adapted the position interface.",
          result: "Prepared the A3U model and interface for retargeting, training and policy validation.",
        },
        collision: {
          kicker: "03 / COLLISION / FOOT MODEL",
          title: "Foot and collision bodies",
          copy: "While investigating A3U's standing oscillation, I inspected the position and extent of its foot and body collisions, and tried a simplified Capsule foot model. I compared geometry, Kp / Kd and action delay in separate checks to distinguish model, control and timing effects.",
          media: "collision",
          visual: "image",
          visualLabel: "COLLISION OVERLAY",
          context: "Foot contact and collision geometry affect standing and landing directly.",
          evidence: "Inspected four-view collision overlays and compared the simplified foot model.",
          result: "Verified collision positions and extents. Their contribution to hardware stability still needed to be assessed alongside control settings.",
        },
        retarget: {
          kicker: "04 / RETARGET / DATA",
          title: "Motion-data retargeting",
          copy: "G1 motions could run on A3U without preserving their quality. I adapted HHTools to retarget PICO / SMPL motion into A3U training data, inspected .npz outputs with any4hdmi and manually filtered poor results before training.",
          media: null,
          visual: "process",
          visualLabel: "PICO / SMPL → RETARGET → NPZ → TRAINING",
          process: ["PICO / SMPL", "motion retarget", ".npz", "policy training"],
          context: "Motion data has to account for A3U's body, not just pass through the G1 deployment code.",
          evidence: "Adapted HHTools, generated .npz motions and inspected them with any4hdmi.",
          result: "Connected capture, retargeting, inspection and training; some outputs still required manual filtering.",
        },
        policy: {
          kicker: "05 / POLICY / SIM",
          title: "Policy and simulation response",
          copy: "I trained the A3U policy on retargeted motion data, checked it in sim2sim and tested it on hardware. The first version could walk, but standing and complex motions remained unstable. I continued adjusting the motion mix and training settings while investigating body and collision differences separately.",
          media: "policy",
          visual: "video",
          visualLabel: "POLICY RESPONSE · SIM2SIM",
          caption: "A3U policy response in MuJoCo sim2sim · no PICO target view or real robot shown",
          context: "Prepare a policy for the new body and verify that its motion survives hardware deployment.",
          evidence: "Trained on A3U data, inspected sim2sim response and carried out hardware checks.",
          result: "Walking worked in simulation and after deployment; standing and complex motions still needed improvement.",
        },
        stability: {
          kicker: "06 / STABILITY DEBUG",
          title: "Hardware stability debugging",
          copy: "The preparation pose held in simulation, yet A3U shook at high frequency on hardware. I compared body response, leg targets and first-frame state to investigate collision, timing and gains separately. After I tuned Kp / Kd and retrained, the obvious shaking largely disappeared and simple motions became much steadier on hardware.",
          media: "diagnosis",
          secondaryMedia: "control",
          visual: "diagnostic",
          visualLabel: "RESPONSE / GAIN DIAGNOSTICS",
          context: "The preparation pose was fine in simulation, while hardware showed high-frequency shaking and a first-frame jump.",
          evidence: "Compared body response and leg targets across Kp / Kd and action-delay settings.",
          result: "Gain tuning and retraining largely removed the visible shaking and enabled steady simple motions.",
        },
        teleop: {
          kicker: "07 / PICO TELEOP",
          title: "PICO teleoperation",
          copy: "I connected PICO input to A3U teleoperation, first checking mapping and policy response in MuJoCo, then testing arm, body and walking motions on hardware. I checked whether the robot matched the input, responded in time and stayed stable throughout the motion.",
          media: "teleopHardware",
          visual: "video",
          visualLabel: "REAL HARDWARE · PICO TELEOP",
          caption: "REAL HARDWARE · PICO operator and A3U in the same recording",
          context: "Turn tracked human input into a corresponding, stable response on the real robot.",
          evidence: "Checked input in MuJoCo and tested A3U teleoperation, with operator and robot recorded together.",
          result: "PICO input drives visible arm following, body movement and walking responses on A3U.",
        },
      },
      outcomeTitle: "Transfer and motion quality",
      outcomeDone: "I took the work from reproducing G1 deployment to adapting A3U's model, data and control interface, then training and testing on hardware. Gain tuning and retraining largely removed the high-frequency shaking. PICO now drives arm, body and walking responses, with simple motions running on the robot.",
      outcomeOpen: "Motion quality is still the harder part. Adding ground motions improved larger movements but degraded some previously stable ones. Shallow squats work; deeper squats can lose stability. I'm continuing to balance the training data and parameters, and performance has not yet matched the original G1 policy.",
      evidenceTitle: "A3U adaptation and validation",
      evidenceIntro: "I adapted A3U's model, motion data and control interface. Model views, simulation plots and hardware tests helped me investigate transfer between different robot bodies.",
      a3uOpenLabel: "Open evidence image at full size",
      a3u: {
        asset: { kicker: "02 / MODEL / URDF", title: "A3U model adaptation", copy: "I integrated the URDF and model files, verified joint order and initial configuration, and inspected the loaded MuJoCo model before preparing motions and training." },
        retarget: { kicker: "04 / RETARGET / DATA", title: "Motion-data retargeting", copy: "I adapted the PICO / SMPL to HHTools retargeting flow, inspected .npz motions with any4hdmi and filtered poor results before A3U policy training." },
        diagnosis: { kicker: "06 / STABILITY DEBUG", title: "Motion and response diagnostics", copy: "I compared body response across motion, speed and delay settings to locate oscillation and tracking errors, then investigated the corresponding model and control parameters." },
        collision: { kicker: "03 / COLLISION / FOOT MODEL", title: "Foot collision", copy: "I inspected foot and body collisions in four-view overlays and tested a simplified Capsule foot model, keeping contact geometry separate from control-gain checks." },
        control: { kicker: "06 / GAIN DIAGNOSTICS", title: "Control gains", copy: "I compared body tilt, gyroscope response and leg targets across Kp / Kd settings, using those responses to guide retuning and retraining." },
        policy: { kicker: "05 / POLICY / SIM", title: "Policy and simulation response", copy: "I checked A3U policy response in sim2real-base-sim before hardware tests. This is the simulation view, with no PICO target or real robot shown." },
        teleop: { kicker: "07 / PICO TELEOP", title: "A3U hardware teleoperation", copy: "I connected PICO input to A3U and checked arm, body and walking responses on hardware. Recording the operator and robot together makes the motion correspondence visible." },
      },
    },
    manipulation: {
      secondaryLabel: "Technical profile",
      profileLabels: { api: "Control API", rate: "FR3 ServoJ loop", environment: "Environment" },
      lead: "I enjoy getting control ideas working on a real arm: keeping a path moving, following a person smoothly and making contact felt at the other end. I built a spline-motion SDK, FR3 teleoperation and 2-DoF force feedback.",
      motionTitle: "Spline Motion SDK",
      motionIntro: "I independently built this SDK with quintic position interpolation, Rodrigues orientation interpolation, corner blending and ServoCart streaming. IK pre-checks, joint-continuity checks and queue throttling handle path transitions and late targets. It has been used on a PUMA footwear factory robot in Putian.",
      teleopTitle: "FR3 Leader–Follower Teleoperation",
      teleopIntro: "I reused my spline SDK's interpolation methods for FR3 teleoperation at low implementation cost. Sampling runs alongside a 125 Hz control loop. Input updates the pending target; I replan from the current state only when switching conditions are met. I compare raw input, filtering, commands and actual position.",
      forceNav: "2-DoF Force Feedback",
      forceTitle: "2‑DoF Contact Torque and Force Feedback",
      forceIntro: "I wanted the operator to feel when the follower meets resistance. On a 2-DoF setup, I implemented gravity compensation, joint following and contact torque feedback. I subtract model-estimated gravity from motor torque, then use hysteresis and an asymmetric low-pass filter to return resistance to the leader.",
    },
    drawry: {
      name: "Drawry",
      secondaryLabel: "My role",
      lead: "I like exploring what AI can add to everyday life. Drawry turns a child's drawing into a story to read together. On the team, I refined features and interaction logic, and helped design and present the prototype for a family reading experience.",
      title: "From a child's drawing to a story",
      intro: "I designed around the child and parent: upload a drawing, generate a story and return to it later. I defined key screens, each step's inputs and outputs, and how drawings, stories and shared-reading records fit together in the family space.",
      steps: { upload: "Upload", understand: "Understand", story: "Generate", family: "Family space" },
      contributionTitle: "My contribution",
      contributions: [
        { title: "Product & interaction", copy: "Refined features and interaction logic, turning the family reading experience into key screens and actions." },
        { title: "AI workflow & prototype", copy: "Defined inputs and outputs for image understanding, stories and storyboards, and contributed to the MVP prototype design." },
        { title: "Validation & demo", copy: "Helped prepare the prototype demonstration and pitch materials, presenting the idea through a complete user flow." },
      ],
      videoCaption: "Product prototype demo · muted",
      states: {
        upload: { kicker: "01 / INPUT", title: "Original drawing", copy: "Upload or capture the drawing and keep the source image.", output: "OUTPUT · ORIGINAL DRAWING" },
        understand: { kicker: "02 / UNDERSTAND", title: "Visual elements", copy: "Identify characters, objects and scenes in the drawing.", output: "OUTPUT · CHARACTERS / SCENE / THEME" },
        story: { kicker: "03 / STORY", title: "Story and storyboard", copy: "Generate a story and storyboard from those visual elements.", output: "OUTPUT · STORY + GENERATED VIDEO" },
        family: { kicker: "04 / FAMILY", title: "Family space", copy: "Save drawings, stories and reading history in the family space.", output: "OUTPUT · ALBUM / PROFILE / READING" },
      },
    },
  };

  const bundle = { shared, zh, en };
  if (typeof window !== "undefined") window.PORTFOLIO_V6 = bundle;
  if (typeof module !== "undefined") module.exports = { PORTFOLIO_V6: bundle };
})();
